version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./telegraf/development.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./telegraf/mongo-dev:/data/db
    command: --wiredTigerCacheSizeGB 2.5
  api-dev:
    container_name: nest-product-dev-api
    build:
      dockerfile: Dockerfile
      context: ./telegraf
      # Только этап разработки будет построен из Dockerfile
      target: development
    volumes:
      - ./telegraf:/usr/src/app
    env_file:
      - ./telegraf/development.env
    command: npm run start:dev
    ports:
      - 5000:5002
    depends_on:
      - mongodb
      - redis
  client-dev:
    build:
      dockerfile: Dockerfile
      context: ./client
      target: development
    container_name: client-product-dev-app
    command: npm run start
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/node_modules:/usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api-dev
  redis:
    container_name: cache
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - ./telegraf/redis:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
volumes:
  redis:
    driver: local  
    
    
    
